
spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: admin
  sql:
    init:
      mode: always
      platform: postgres
  servlet:
    multipart:
      max-file-size: 10MB


chat-app:
  security:
    jwt:
      secret: "jwtSecret123nosdfj"
      expiration-hours: 24

aws:
  bucket: "jszmidla-chatapp"