
spring:
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: postgres
  servlet:
    multipart:
      max-file-size: 10MB

chat-app:
  security:
    jwt:
      secret: "jwtSecret123nosdfj"
      expiration-hours: 24

aws:
  bucket: "jszmidla-chatapp"

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: admin

aws:
  bucket: "jszmidla-chatapp"
  frontend:
    origin: 'http://localhost:5173'